# Generated by Django 4.1.2 on 2022-10-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_foodmenu_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id'], 'verbose_name': 'Client', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='tablefood',
            options={'ordering': ['id'], 'verbose_name': 'TableFlood', 'verbose_name_plural': 'TableFloods'},
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='products',
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='client',
            field=models.ManyToManyField(blank=True, through='orders.FoodMenu', to='orders.client'),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
